version: "3.9"
services:  
  web:
    build: .
    volumes:
      - .:/aplicacao
    ports:
      - "3000:3000"
    depends_on:
      - db
      
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - web